

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Localisation : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Localisation entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Localisation()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Localisation(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Localisation> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Localisation.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisation_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisation_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AdresseComplete
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.AdresseComplete);
            }
            set
            {
                global::LightSwitchApplication.Localisation.DetailsClass.SetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.AdresseComplete, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AdresseComplete_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AdresseComplete_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AdresseComplete_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Latitude
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Latitude);
            }
            set
            {
                global::LightSwitchApplication.Localisation.DetailsClass.SetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Latitude, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Latitude_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Latitude_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Latitude_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Longitude
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Longitude);
            }
            set
            {
                global::LightSwitchApplication.Localisation.DetailsClass.SetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Longitude, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Longitude_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Longitude_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Longitude_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UrlBingMapImage
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.UrlBingMapImage);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UrlBingMapImage_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UrlBingMapImage_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Client> Clients
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Clients);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Client> ClientsQuery
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetQuery(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Clients);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Prestataire> Prestataires
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Prestataires);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Prestataire> PrestatairesQuery
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetQuery(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Prestataires);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Zone> Zones
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Zones);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Zone> ZonesQuery
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetQuery(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Zones);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Zone> Zones1
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetValue(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Zones1);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Zone> Zones1Query
        {
            get
            {
                return global::LightSwitchApplication.Localisation.DetailsClass.GetQuery(this, global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Zones1);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Localisation,
                global::LightSwitchApplication.Localisation.DetailsClass,
                global::LightSwitchApplication.Localisation.DetailsClass.IImplementation,
                global::LightSwitchApplication.Localisation.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass>.Entry
                __LocalisationEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass>.Entry(
                    global::LightSwitchApplication.Localisation.DetailsClass.__Localisation_CreateNew,
                    global::LightSwitchApplication.Localisation.DetailsClass.__Localisation_Created,
                    global::LightSwitchApplication.Localisation.DetailsClass.__Localisation_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Localisation __Localisation_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Localisation> es)
            {
                return new global::LightSwitchApplication.Localisation(es);
            }
            private static void __Localisation_Created(global::LightSwitchApplication.Localisation e)
            {
                e.Localisation_Created();
            }
            private static bool __Localisation_AllowSaveWithErrors(global::LightSwitchApplication.Localisation e)
            {
                bool result = false;
                e.Localisation_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Localisation.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string> AdresseComplete
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.AdresseComplete) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string> Latitude
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Latitude) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string> Longitude
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Longitude) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string> UrlBingMapImage
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.UrlBingMapImage) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Client> Clients
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Clients) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Client>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Prestataire> Prestataires
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Prestataires) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Prestataire>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone> Zones
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Zones) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone> Zones1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Zones1) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string AdresseComplete { get; set; }
                new string Latitude { get; set; }
                new string Longitude { get; set; }
                new global::System.Collections.IEnumerable Clients { get; }
                new global::System.Collections.IEnumerable Prestataires { get; }
                new global::System.Collections.IEnumerable Zones { get; }
                new global::System.Collections.IEnumerable Zones1 { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, int>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Localisation e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Localisation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Localisation e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Entry
                    AdresseComplete = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Entry(
                        "AdresseComplete",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._AdresseComplete_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._AdresseComplete_ComputeIsReadOnly,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._AdresseComplete_Validate,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._AdresseComplete_GetImplementationValue,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._AdresseComplete_SetImplementationValue,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._AdresseComplete_OnValueChanged);
                private static void _AdresseComplete_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._AdresseComplete, sf);
                }
                private static bool _AdresseComplete_ComputeIsReadOnly(global::LightSwitchApplication.Localisation e)
                {
                    bool result = false;
                    e.AdresseComplete_IsReadOnly(ref result);
                    return result;
                }
                private static void _AdresseComplete_Validate(global::LightSwitchApplication.Localisation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AdresseComplete_Validate(r);
                }
                private static string _AdresseComplete_GetImplementationValue(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.ImplementationEntity.AdresseComplete;
                }
                private static void _AdresseComplete_SetImplementationValue(global::LightSwitchApplication.Localisation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.AdresseComplete = v;
                }
                private static void _AdresseComplete_OnValueChanged(global::LightSwitchApplication.Localisation e)
                {
                    e.AdresseComplete_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Entry
                    Latitude = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Entry(
                        "Latitude",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Latitude_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Latitude_ComputeIsReadOnly,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Latitude_Validate,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Latitude_GetImplementationValue,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Latitude_SetImplementationValue,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Latitude_OnValueChanged);
                private static void _Latitude_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._Latitude, sf);
                }
                private static bool _Latitude_ComputeIsReadOnly(global::LightSwitchApplication.Localisation e)
                {
                    bool result = false;
                    e.Latitude_IsReadOnly(ref result);
                    return result;
                }
                private static void _Latitude_Validate(global::LightSwitchApplication.Localisation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Latitude_Validate(r);
                }
                private static string _Latitude_GetImplementationValue(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.ImplementationEntity.Latitude;
                }
                private static void _Latitude_SetImplementationValue(global::LightSwitchApplication.Localisation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Latitude = v;
                }
                private static void _Latitude_OnValueChanged(global::LightSwitchApplication.Localisation e)
                {
                    e.Latitude_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Entry
                    Longitude = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Entry(
                        "Longitude",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Longitude_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Longitude_ComputeIsReadOnly,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Longitude_Validate,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Longitude_GetImplementationValue,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Longitude_SetImplementationValue,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Longitude_OnValueChanged);
                private static void _Longitude_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._Longitude, sf);
                }
                private static bool _Longitude_ComputeIsReadOnly(global::LightSwitchApplication.Localisation e)
                {
                    bool result = false;
                    e.Longitude_IsReadOnly(ref result);
                    return result;
                }
                private static void _Longitude_Validate(global::LightSwitchApplication.Localisation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Longitude_Validate(r);
                }
                private static string _Longitude_GetImplementationValue(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.ImplementationEntity.Longitude;
                }
                private static void _Longitude_SetImplementationValue(global::LightSwitchApplication.Localisation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Longitude = v;
                }
                private static void _Longitude_OnValueChanged(global::LightSwitchApplication.Localisation e)
                {
                    e.Longitude_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Entry
                    UrlBingMapImage = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Entry(
                        "UrlBingMapImage",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._UrlBingMapImage_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._UrlBingMapImage_Validate,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._UrlBingMapImage_ComputeValue);
                private static void _UrlBingMapImage_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._UrlBingMapImage, sf);
                }
                private static void _UrlBingMapImage_Validate(global::LightSwitchApplication.Localisation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UrlBingMapImage_Validate(r);
                }
                private static string _UrlBingMapImage_ComputeValue(global::LightSwitchApplication.Localisation e)
                {
                    string value = default(string);
                    e.UrlBingMapImage_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Client>.Entry
                    Clients = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Client>.Entry(
                        "Clients",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Clients_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Clients_GetReferencedEntities,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Clients_GetEntityCollection);
                private static void _Clients_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Client>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._Clients, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Client> _Clients_GetReferencedEntities(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Clients, ref d._Clients);
                }
                private static global::System.Collections.IEnumerable _Clients_GetEntityCollection(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.ImplementationEntity.Clients;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Prestataire>.Entry
                    Prestataires = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Prestataire>.Entry(
                        "Prestataires",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Prestataires_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Prestataires_GetReferencedEntities,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Prestataires_GetEntityCollection);
                private static void _Prestataires_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Prestataire>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._Prestataires, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Prestataire> _Prestataires_GetReferencedEntities(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass>(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Prestataires, ref d._Prestataires);
                }
                private static global::System.Collections.IEnumerable _Prestataires_GetEntityCollection(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.ImplementationEntity.Prestataires;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>.Entry
                    Zones = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>.Entry(
                        "Zones",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Zones_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Zones_GetReferencedEntities,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Zones_GetEntityCollection);
                private static void _Zones_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._Zones, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Zone> _Zones_GetReferencedEntities(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Zone, global::LightSwitchApplication.Zone.DetailsClass>(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Zones, ref d._Zones);
                }
                private static global::System.Collections.IEnumerable _Zones_GetEntityCollection(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.ImplementationEntity.Zones;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>.Entry
                    Zones1 = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>.Entry(
                        "Zones1",
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Zones1_Stub,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Zones1_GetReferencedEntities,
                        global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties._Zones1_GetEntityCollection);
                private static void _Zones1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Localisation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>.Data> c, global::LightSwitchApplication.Localisation.DetailsClass d, object sf)
                {
                    c(d, ref d._Zones1, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Zone> _Zones1_GetReferencedEntities(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Zone, global::LightSwitchApplication.Zone.DetailsClass>(global::LightSwitchApplication.Localisation.DetailsClass.PropertySetProperties.Zones1, ref d._Zones1);
                }
                private static global::System.Collections.IEnumerable _Zones1_GetEntityCollection(global::LightSwitchApplication.Localisation.DetailsClass d)
                {
                    return d.ImplementationEntity.Zones1;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Data _AdresseComplete;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Data _Latitude;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Data _Longitude;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, string>.Data _UrlBingMapImage;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Client>.Data _Clients;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Prestataire>.Data _Prestataires;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>.Data _Zones;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass, global::LightSwitchApplication.Zone>.Data _Zones1;
            
        }
    
        #endregion
    }
    
    #endregion
}
