

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Intervention : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Intervention entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Intervention()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Intervention(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Intervention> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Intervention.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Intervention_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Intervention_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Intervention.DetailsClass.GetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateDebut
        {
            get
            {
                return global::LightSwitchApplication.Intervention.DetailsClass.GetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.DateDebut);
            }
            set
            {
                global::LightSwitchApplication.Intervention.DetailsClass.SetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.DateDebut, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDebut_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDebut_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDebut_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateFin
        {
            get
            {
                return global::LightSwitchApplication.Intervention.DetailsClass.GetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.DateFin);
            }
            set
            {
                global::LightSwitchApplication.Intervention.DetailsClass.SetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.DateFin, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateFin_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateFin_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateFin_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Poste
        {
            get
            {
                return global::LightSwitchApplication.Intervention.DetailsClass.GetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Poste);
            }
            set
            {
                global::LightSwitchApplication.Intervention.DetailsClass.SetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Poste, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Poste_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Poste_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Poste_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Client Client1
        {
            get
            {
                return global::LightSwitchApplication.Intervention.DetailsClass.GetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Client1);
            }
            set
            {
                global::LightSwitchApplication.Intervention.DetailsClass.SetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Client1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Prestataire Prestataire1
        {
            get
            {
                return global::LightSwitchApplication.Intervention.DetailsClass.GetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Prestataire1);
            }
            set
            {
                global::LightSwitchApplication.Intervention.DetailsClass.SetValue(this, global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Prestataire1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataire1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataire1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataire1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Intervention,
                global::LightSwitchApplication.Intervention.DetailsClass,
                global::LightSwitchApplication.Intervention.DetailsClass.IImplementation,
                global::LightSwitchApplication.Intervention.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass>.Entry
                __InterventionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass>.Entry(
                    global::LightSwitchApplication.Intervention.DetailsClass.__Intervention_CreateNew,
                    global::LightSwitchApplication.Intervention.DetailsClass.__Intervention_Created,
                    global::LightSwitchApplication.Intervention.DetailsClass.__Intervention_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Intervention __Intervention_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Intervention> es)
            {
                return new global::LightSwitchApplication.Intervention(es);
            }
            private static void __Intervention_Created(global::LightSwitchApplication.Intervention e)
            {
                e.Intervention_Created();
            }
            private static bool __Intervention_AllowSaveWithErrors(global::LightSwitchApplication.Intervention e)
            {
                bool result = false;
                e.Intervention_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Intervention.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.DateTime> DateDebut
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.DateDebut) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.Nullable<global::System.DateTime>> DateFin
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.DateFin) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, string> Poste
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Poste) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Client> Client1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Client1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Client>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Prestataire> Prestataire1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Prestataire1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Prestataire>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new global::System.DateTime DateDebut { get; set; }
                new global::System.Nullable<global::System.DateTime> DateFin { get; set; }
                new string Poste { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Client1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Prestataire1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Intervention.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, int>.Data> c, global::LightSwitchApplication.Intervention.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Intervention e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Intervention e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Intervention e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.DateTime>.Entry
                    DateDebut = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.DateTime>.Entry(
                        "DateDebut",
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateDebut_Stub,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateDebut_ComputeIsReadOnly,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateDebut_Validate,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateDebut_GetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateDebut_SetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateDebut_OnValueChanged);
                private static void _DateDebut_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Intervention.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Intervention.DetailsClass d, object sf)
                {
                    c(d, ref d._DateDebut, sf);
                }
                private static bool _DateDebut_ComputeIsReadOnly(global::LightSwitchApplication.Intervention e)
                {
                    bool result = false;
                    e.DateDebut_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateDebut_Validate(global::LightSwitchApplication.Intervention e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateDebut_Validate(r);
                }
                private static global::System.DateTime _DateDebut_GetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    return d.ImplementationEntity.DateDebut;
                }
                private static void _DateDebut_SetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateDebut = global::LightSwitchApplication.Intervention.DetailsClass.TruncateDate(v);
                }
                private static void _DateDebut_OnValueChanged(global::LightSwitchApplication.Intervention e)
                {
                    e.DateDebut_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateFin = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateFin",
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateFin_Stub,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateFin_ComputeIsReadOnly,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateFin_Validate,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateFin_GetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateFin_SetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._DateFin_OnValueChanged);
                private static void _DateFin_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Intervention.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Intervention.DetailsClass d, object sf)
                {
                    c(d, ref d._DateFin, sf);
                }
                private static bool _DateFin_ComputeIsReadOnly(global::LightSwitchApplication.Intervention e)
                {
                    bool result = false;
                    e.DateFin_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateFin_Validate(global::LightSwitchApplication.Intervention e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateFin_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateFin_GetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    return d.ImplementationEntity.DateFin;
                }
                private static void _DateFin_SetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateFin = global::LightSwitchApplication.Intervention.DetailsClass.TruncateDate(v);
                }
                private static void _DateFin_OnValueChanged(global::LightSwitchApplication.Intervention e)
                {
                    e.DateFin_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, string>.Entry
                    Poste = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, string>.Entry(
                        "Poste",
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Poste_Stub,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Poste_ComputeIsReadOnly,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Poste_Validate,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Poste_GetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Poste_SetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Poste_OnValueChanged);
                private static void _Poste_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Intervention.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, string>.Data> c, global::LightSwitchApplication.Intervention.DetailsClass d, object sf)
                {
                    c(d, ref d._Poste, sf);
                }
                private static bool _Poste_ComputeIsReadOnly(global::LightSwitchApplication.Intervention e)
                {
                    bool result = false;
                    e.Poste_IsReadOnly(ref result);
                    return result;
                }
                private static void _Poste_Validate(global::LightSwitchApplication.Intervention e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Poste_Validate(r);
                }
                private static string _Poste_GetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    return d.ImplementationEntity.Poste;
                }
                private static void _Poste_SetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Poste = v;
                }
                private static void _Poste_OnValueChanged(global::LightSwitchApplication.Intervention e)
                {
                    e.Poste_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Client>.Entry
                    Client1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Client>.Entry(
                        "Client1",
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Client1_Stub,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Client1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Client1_Validate,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Client1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Client1_GetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Client1_SetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Client1_Refresh,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Client1_OnValueChanged);
                private static void _Client1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Intervention.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Client>.Data> c, global::LightSwitchApplication.Intervention.DetailsClass d, object sf)
                {
                    c(d, ref d._Client1, sf);
                }
                private static bool _Client1_ComputeIsReadOnly(global::LightSwitchApplication.Intervention e)
                {
                    bool result = false;
                    e.Client1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Client1_Validate(global::LightSwitchApplication.Intervention e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Client1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Client1_GetCoreImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    return d.ImplementationEntity.Client1;
                }
                private static global::LightSwitchApplication.Client _Client1_GetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Client1, ref d._Client1);
                }
                private static void _Client1_SetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d, global::LightSwitchApplication.Client v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Client1, ref d._Client1, (i, ev) => i.Client1 = ev, v);
                }
                private static void _Client1_Refresh(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Client1, ref d._Client1);
                }
                private static void _Client1_OnValueChanged(global::LightSwitchApplication.Intervention e)
                {
                    e.Client1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Prestataire>.Entry
                    Prestataire1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Prestataire>.Entry(
                        "Prestataire1",
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Prestataire1_Stub,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Prestataire1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Prestataire1_Validate,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Prestataire1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Prestataire1_GetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Prestataire1_SetImplementationValue,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Prestataire1_Refresh,
                        global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties._Prestataire1_OnValueChanged);
                private static void _Prestataire1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Intervention.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Prestataire>.Data> c, global::LightSwitchApplication.Intervention.DetailsClass d, object sf)
                {
                    c(d, ref d._Prestataire1, sf);
                }
                private static bool _Prestataire1_ComputeIsReadOnly(global::LightSwitchApplication.Intervention e)
                {
                    bool result = false;
                    e.Prestataire1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Prestataire1_Validate(global::LightSwitchApplication.Intervention e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Prestataire1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Prestataire1_GetCoreImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    return d.ImplementationEntity.Prestataire1;
                }
                private static global::LightSwitchApplication.Prestataire _Prestataire1_GetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass>(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Prestataire1, ref d._Prestataire1);
                }
                private static void _Prestataire1_SetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass d, global::LightSwitchApplication.Prestataire v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Prestataire1, ref d._Prestataire1, (i, ev) => i.Prestataire1 = ev, v);
                }
                private static void _Prestataire1_Refresh(global::LightSwitchApplication.Intervention.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Intervention.DetailsClass.PropertySetProperties.Prestataire1, ref d._Prestataire1);
                }
                private static void _Prestataire1_OnValueChanged(global::LightSwitchApplication.Intervention e)
                {
                    e.Prestataire1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.DateTime>.Data _DateDebut;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateFin;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, string>.Data _Poste;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Client>.Data _Client1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass, global::LightSwitchApplication.Prestataire>.Data _Prestataire1;
            
        }
    
        #endregion
    }
    
    #endregion
}
