

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Client : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Client entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Client()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Client(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Client> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Client.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Client.DetailsClass.GetValue(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Nom
        {
            get
            {
                return global::LightSwitchApplication.Client.DetailsClass.GetValue(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Nom);
            }
            set
            {
                global::LightSwitchApplication.Client.DetailsClass.SetValue(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Nom, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nom_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nom_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Localisation Localisation1
        {
            get
            {
                return global::LightSwitchApplication.Client.DetailsClass.GetValue(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Localisation1);
            }
            set
            {
                global::LightSwitchApplication.Client.DetailsClass.SetValue(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Localisation1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisation1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisation1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisation1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Zone Zone1
        {
            get
            {
                return global::LightSwitchApplication.Client.DetailsClass.GetValue(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Zone1);
            }
            set
            {
                global::LightSwitchApplication.Client.DetailsClass.SetValue(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Zone1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zone1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zone1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zone1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Intervention> Interventions
        {
            get
            {
                return global::LightSwitchApplication.Client.DetailsClass.GetValue(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Interventions);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Intervention> InterventionsQuery
        {
            get
            {
                return global::LightSwitchApplication.Client.DetailsClass.GetQuery(this, global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Interventions);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Client,
                global::LightSwitchApplication.Client.DetailsClass,
                global::LightSwitchApplication.Client.DetailsClass.IImplementation,
                global::LightSwitchApplication.Client.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>.Entry
                __ClientEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>.Entry(
                    global::LightSwitchApplication.Client.DetailsClass.__Client_CreateNew,
                    global::LightSwitchApplication.Client.DetailsClass.__Client_Created,
                    global::LightSwitchApplication.Client.DetailsClass.__Client_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Client __Client_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Client> es)
            {
                return new global::LightSwitchApplication.Client(es);
            }
            private static void __Client_Created(global::LightSwitchApplication.Client e)
            {
                e.Client_Created();
            }
            private static bool __Client_AllowSaveWithErrors(global::LightSwitchApplication.Client e)
            {
                bool result = false;
                e.Client_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Client.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, string> Nom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Nom) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Localisation> Localisation1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Localisation1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Localisation>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Zone> Zone1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Zone1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Zone>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Intervention> Interventions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Interventions) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Intervention>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Nom { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Localisation1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Zone1 { get; set; }
                new global::System.Collections.IEnumerable Interventions { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Client.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, int>.Data> c, global::LightSwitchApplication.Client.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Client e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Client e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Client e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, string>.Entry
                    Nom = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, string>.Entry(
                        "Nom",
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Nom_Stub,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Nom_ComputeIsReadOnly,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Nom_Validate,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Nom_GetImplementationValue,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Nom_SetImplementationValue,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Nom_OnValueChanged);
                private static void _Nom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Client.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, string>.Data> c, global::LightSwitchApplication.Client.DetailsClass d, object sf)
                {
                    c(d, ref d._Nom, sf);
                }
                private static bool _Nom_ComputeIsReadOnly(global::LightSwitchApplication.Client e)
                {
                    bool result = false;
                    e.Nom_IsReadOnly(ref result);
                    return result;
                }
                private static void _Nom_Validate(global::LightSwitchApplication.Client e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Nom_Validate(r);
                }
                private static string _Nom_GetImplementationValue(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    return d.ImplementationEntity.Nom;
                }
                private static void _Nom_SetImplementationValue(global::LightSwitchApplication.Client.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Nom = v;
                }
                private static void _Nom_OnValueChanged(global::LightSwitchApplication.Client e)
                {
                    e.Nom_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Localisation>.Entry
                    Localisation1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Localisation>.Entry(
                        "Localisation1",
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Localisation1_Stub,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Localisation1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Localisation1_Validate,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Localisation1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Localisation1_GetImplementationValue,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Localisation1_SetImplementationValue,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Localisation1_Refresh,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Localisation1_OnValueChanged);
                private static void _Localisation1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Client.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Localisation>.Data> c, global::LightSwitchApplication.Client.DetailsClass d, object sf)
                {
                    c(d, ref d._Localisation1, sf);
                }
                private static bool _Localisation1_ComputeIsReadOnly(global::LightSwitchApplication.Client e)
                {
                    bool result = false;
                    e.Localisation1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Localisation1_Validate(global::LightSwitchApplication.Client e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Localisation1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Localisation1_GetCoreImplementationValue(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    return d.ImplementationEntity.Localisation1;
                }
                private static global::LightSwitchApplication.Localisation _Localisation1_GetImplementationValue(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass>(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Localisation1, ref d._Localisation1);
                }
                private static void _Localisation1_SetImplementationValue(global::LightSwitchApplication.Client.DetailsClass d, global::LightSwitchApplication.Localisation v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Localisation1, ref d._Localisation1, (i, ev) => i.Localisation1 = ev, v);
                }
                private static void _Localisation1_Refresh(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Localisation1, ref d._Localisation1);
                }
                private static void _Localisation1_OnValueChanged(global::LightSwitchApplication.Client e)
                {
                    e.Localisation1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Zone>.Entry
                    Zone1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Zone>.Entry(
                        "Zone1",
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Zone1_Stub,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Zone1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Zone1_Validate,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Zone1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Zone1_GetImplementationValue,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Zone1_SetImplementationValue,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Zone1_Refresh,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Zone1_OnValueChanged);
                private static void _Zone1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Client.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Zone>.Data> c, global::LightSwitchApplication.Client.DetailsClass d, object sf)
                {
                    c(d, ref d._Zone1, sf);
                }
                private static bool _Zone1_ComputeIsReadOnly(global::LightSwitchApplication.Client e)
                {
                    bool result = false;
                    e.Zone1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Zone1_Validate(global::LightSwitchApplication.Client e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Zone1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Zone1_GetCoreImplementationValue(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    return d.ImplementationEntity.Zone1;
                }
                private static global::LightSwitchApplication.Zone _Zone1_GetImplementationValue(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Zone, global::LightSwitchApplication.Zone.DetailsClass>(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Zone1, ref d._Zone1);
                }
                private static void _Zone1_SetImplementationValue(global::LightSwitchApplication.Client.DetailsClass d, global::LightSwitchApplication.Zone v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Zone1, ref d._Zone1, (i, ev) => i.Zone1 = ev, v);
                }
                private static void _Zone1_Refresh(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Zone1, ref d._Zone1);
                }
                private static void _Zone1_OnValueChanged(global::LightSwitchApplication.Client e)
                {
                    e.Zone1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Intervention>.Entry
                    Interventions = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Intervention>.Entry(
                        "Interventions",
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Interventions_Stub,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Interventions_GetReferencedEntities,
                        global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties._Interventions_GetEntityCollection);
                private static void _Interventions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Client.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Intervention>.Data> c, global::LightSwitchApplication.Client.DetailsClass d, object sf)
                {
                    c(d, ref d._Interventions, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Intervention> _Interventions_GetReferencedEntities(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass>(global::LightSwitchApplication.Client.DetailsClass.PropertySetProperties.Interventions, ref d._Interventions);
                }
                private static global::System.Collections.IEnumerable _Interventions_GetEntityCollection(global::LightSwitchApplication.Client.DetailsClass d)
                {
                    return d.ImplementationEntity.Interventions;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, string>.Data _Nom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Localisation>.Data _Localisation1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Zone>.Data _Zone1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass, global::LightSwitchApplication.Intervention>.Data _Interventions;
            
        }
    
        #endregion
    }
    
    #endregion
}
