//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the DBPrestaConnectData datasource.
    /// </summary>
    public sealed partial class DBPrestaConnectDataService
        : global::LightSwitchApplication.DBPrestaConnectData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DBPrestaConnectDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_Inserting(global::LightSwitchApplication.Client entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_Inserted(global::LightSwitchApplication.Client entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_Updating(global::LightSwitchApplication.Client entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_Updated(global::LightSwitchApplication.Client entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_Deleting(global::LightSwitchApplication.Client entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_Deleted(global::LightSwitchApplication.Client entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_Validate(global::LightSwitchApplication.Client entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clients_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Client, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_Inserting(global::LightSwitchApplication.Intervention entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_Inserted(global::LightSwitchApplication.Intervention entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_Updating(global::LightSwitchApplication.Intervention entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_Updated(global::LightSwitchApplication.Intervention entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_Deleting(global::LightSwitchApplication.Intervention entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_Deleted(global::LightSwitchApplication.Intervention entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_Validate(global::LightSwitchApplication.Intervention entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interventions_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Intervention, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_Inserting(global::LightSwitchApplication.Localisation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_Inserted(global::LightSwitchApplication.Localisation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_Updating(global::LightSwitchApplication.Localisation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_Updated(global::LightSwitchApplication.Localisation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_Deleting(global::LightSwitchApplication.Localisation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_Deleted(global::LightSwitchApplication.Localisation entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_Validate(global::LightSwitchApplication.Localisation entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisations_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Localisation, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_Inserting(global::LightSwitchApplication.Prestataire entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_Inserted(global::LightSwitchApplication.Prestataire entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_Updating(global::LightSwitchApplication.Prestataire entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_Updated(global::LightSwitchApplication.Prestataire entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_Deleting(global::LightSwitchApplication.Prestataire entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_Deleted(global::LightSwitchApplication.Prestataire entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_Validate(global::LightSwitchApplication.Prestataire entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataires_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Prestataire, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_Inserting(global::LightSwitchApplication.Zone entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_Inserted(global::LightSwitchApplication.Zone entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_Updating(global::LightSwitchApplication.Zone entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_Updated(global::LightSwitchApplication.Zone entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_Deleting(global::LightSwitchApplication.Zone entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_Deleted(global::LightSwitchApplication.Zone entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_Validate(global::LightSwitchApplication.Zone entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zones_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Zone, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DBPrestaConnectData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Client>
                __ClientsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Client>(
                    "Clients",
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_CanInsert,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_CanUpdate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_CanDelete,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_CanRead,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_Inserting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_Inserted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_Updating,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_Updated,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_Deleting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_Deleted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_Validate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Clients_Filter);
            private static bool __Clients_CanInsert(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Clients_CanInsert(ref result);
                return result;
            }
            private static bool __Clients_CanUpdate(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Clients_CanUpdate(ref result);
                return result;
            }
            private static bool __Clients_CanDelete(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Clients_CanDelete(ref result);
                return result;
            }
            private static bool __Clients_CanRead(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Clients_CanRead(ref result);
                return result;
            }
            private static void __Clients_Inserting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Client e)
            {
                d.Clients_Inserting(e);
            }
            private static void __Clients_Inserted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Client e)
            {
                d.Clients_Inserted(e);
            }
            private static void __Clients_Updating(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Client e)
            {
                d.Clients_Updating(e);
            }
            private static void __Clients_Updated(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Client e)
            {
                d.Clients_Updated(e);
            }
            private static void __Clients_Deleting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Client e)
            {
                d.Clients_Deleting(e);
            }
            private static void __Clients_Deleted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Client e)
            {
                d.Clients_Deleted(e);
            }
            private static void __Clients_Validate(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Client e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Clients_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Client, bool>> __Clients_Filter(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Client, bool>> filter = null;
                d.Clients_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Intervention>
                __InterventionsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Intervention>(
                    "Interventions",
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_CanInsert,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_CanUpdate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_CanDelete,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_CanRead,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_Inserting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_Inserted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_Updating,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_Updated,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_Deleting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_Deleted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_Validate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Interventions_Filter);
            private static bool __Interventions_CanInsert(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Interventions_CanInsert(ref result);
                return result;
            }
            private static bool __Interventions_CanUpdate(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Interventions_CanUpdate(ref result);
                return result;
            }
            private static bool __Interventions_CanDelete(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Interventions_CanDelete(ref result);
                return result;
            }
            private static bool __Interventions_CanRead(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Interventions_CanRead(ref result);
                return result;
            }
            private static void __Interventions_Inserting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Intervention e)
            {
                d.Interventions_Inserting(e);
            }
            private static void __Interventions_Inserted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Intervention e)
            {
                d.Interventions_Inserted(e);
            }
            private static void __Interventions_Updating(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Intervention e)
            {
                d.Interventions_Updating(e);
            }
            private static void __Interventions_Updated(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Intervention e)
            {
                d.Interventions_Updated(e);
            }
            private static void __Interventions_Deleting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Intervention e)
            {
                d.Interventions_Deleting(e);
            }
            private static void __Interventions_Deleted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Intervention e)
            {
                d.Interventions_Deleted(e);
            }
            private static void __Interventions_Validate(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Intervention e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Interventions_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Intervention, bool>> __Interventions_Filter(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Intervention, bool>> filter = null;
                d.Interventions_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Localisation>
                __LocalisationsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Localisation>(
                    "Localisations",
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_CanInsert,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_CanUpdate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_CanDelete,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_CanRead,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_Inserting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_Inserted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_Updating,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_Updated,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_Deleting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_Deleted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_Validate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Localisations_Filter);
            private static bool __Localisations_CanInsert(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Localisations_CanInsert(ref result);
                return result;
            }
            private static bool __Localisations_CanUpdate(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Localisations_CanUpdate(ref result);
                return result;
            }
            private static bool __Localisations_CanDelete(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Localisations_CanDelete(ref result);
                return result;
            }
            private static bool __Localisations_CanRead(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Localisations_CanRead(ref result);
                return result;
            }
            private static void __Localisations_Inserting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Localisation e)
            {
                d.Localisations_Inserting(e);
            }
            private static void __Localisations_Inserted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Localisation e)
            {
                d.Localisations_Inserted(e);
            }
            private static void __Localisations_Updating(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Localisation e)
            {
                d.Localisations_Updating(e);
            }
            private static void __Localisations_Updated(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Localisation e)
            {
                d.Localisations_Updated(e);
            }
            private static void __Localisations_Deleting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Localisation e)
            {
                d.Localisations_Deleting(e);
            }
            private static void __Localisations_Deleted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Localisation e)
            {
                d.Localisations_Deleted(e);
            }
            private static void __Localisations_Validate(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Localisation e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Localisations_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Localisation, bool>> __Localisations_Filter(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Localisation, bool>> filter = null;
                d.Localisations_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Prestataire>
                __PrestatairesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Prestataire>(
                    "Prestataires",
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_CanInsert,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_CanUpdate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_CanDelete,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_CanRead,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_Inserting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_Inserted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_Updating,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_Updated,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_Deleting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_Deleted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_Validate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Prestataires_Filter);
            private static bool __Prestataires_CanInsert(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Prestataires_CanInsert(ref result);
                return result;
            }
            private static bool __Prestataires_CanUpdate(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Prestataires_CanUpdate(ref result);
                return result;
            }
            private static bool __Prestataires_CanDelete(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Prestataires_CanDelete(ref result);
                return result;
            }
            private static bool __Prestataires_CanRead(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Prestataires_CanRead(ref result);
                return result;
            }
            private static void __Prestataires_Inserting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Prestataire e)
            {
                d.Prestataires_Inserting(e);
            }
            private static void __Prestataires_Inserted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Prestataire e)
            {
                d.Prestataires_Inserted(e);
            }
            private static void __Prestataires_Updating(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Prestataire e)
            {
                d.Prestataires_Updating(e);
            }
            private static void __Prestataires_Updated(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Prestataire e)
            {
                d.Prestataires_Updated(e);
            }
            private static void __Prestataires_Deleting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Prestataire e)
            {
                d.Prestataires_Deleting(e);
            }
            private static void __Prestataires_Deleted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Prestataire e)
            {
                d.Prestataires_Deleted(e);
            }
            private static void __Prestataires_Validate(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Prestataires_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Prestataire, bool>> __Prestataires_Filter(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Prestataire, bool>> filter = null;
                d.Prestataires_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Zone>
                __ZonesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.DBPrestaConnectDataService, global::LightSwitchApplication.Zone>(
                    "Zones",
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_CanInsert,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_CanUpdate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_CanDelete,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_CanRead,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_Inserting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_Inserted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_Updating,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_Updated,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_Deleting,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_Deleted,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_Validate,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Zones_Filter);
            private static bool __Zones_CanInsert(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Zones_CanInsert(ref result);
                return result;
            }
            private static bool __Zones_CanUpdate(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Zones_CanUpdate(ref result);
                return result;
            }
            private static bool __Zones_CanDelete(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Zones_CanDelete(ref result);
                return result;
            }
            private static bool __Zones_CanRead(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                bool result = true;
                d.Zones_CanRead(ref result);
                return result;
            }
            private static void __Zones_Inserting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Zone e)
            {
                d.Zones_Inserting(e);
            }
            private static void __Zones_Inserted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Zone e)
            {
                d.Zones_Inserted(e);
            }
            private static void __Zones_Updating(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Zone e)
            {
                d.Zones_Updating(e);
            }
            private static void __Zones_Updated(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Zone e)
            {
                d.Zones_Updated(e);
            }
            private static void __Zones_Deleting(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Zone e)
            {
                d.Zones_Deleting(e);
            }
            private static void __Zones_Deleted(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Zone e)
            {
                d.Zones_Deleted(e);
            }
            private static void __Zones_Validate(global::LightSwitchApplication.DBPrestaConnectDataService d, global::LightSwitchApplication.Zone e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Zones_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Zone, bool>> __Zones_Filter(global::LightSwitchApplication.DBPrestaConnectDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Zone, bool>> filter = null;
                d.Zones_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.DBPrestaConnectDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.DBPrestaConnectDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.DBPrestaConnectDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.DBPrestaConnectDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.DBPrestaConnectDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.DBPrestaConnectDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.DBPrestaConnectDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.DBPrestaConnectDataService>(
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.DBPrestaConnectDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.DBPrestaConnectDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.DBPrestaConnectDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.DBPrestaConnectDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.DBPrestaConnectDataService>(
                    global::LightSwitchApplication.DBPrestaConnectDataService.DetailsClass.__DBPrestaConnectData_InitializingConnection);
            private static void __DBPrestaConnectData_InitializingConnection(global::LightSwitchApplication.DBPrestaConnectDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.DBPrestaConnectData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
