//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Intervention_ToClient", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Client), "Intervention", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Intervention), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Client_ToLocalisation", "Localisation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Localisation), "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Client), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Prestataire_ToLocalisation", "Localisation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Localisation), "Prestataire", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Prestataire), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Zone_ToLocalisationNO", "Localisation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Localisation), "Zone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Zone), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Zone_ToLocalisationSE", "Localisation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Localisation), "Zone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Zone), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Intervention_ToPrestataire", "Prestataire", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Prestataire), "Intervention", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Intervention), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FK_Client_ToZone", "Zone", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Zone), "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Client), true)]

#endregion

namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBPrestaConnectData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBPrestaConnectData object using the connection string found in the 'DBPrestaConnectData' section of the application configuration file.
        /// </summary>
        public DBPrestaConnectData() : base("name=DBPrestaConnectData", "DBPrestaConnectData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBPrestaConnectData object.
        /// </summary>
        public DBPrestaConnectData(string connectionString) : base(connectionString, "DBPrestaConnectData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBPrestaConnectData object.
        /// </summary>
        public DBPrestaConnectData(EntityConnection connection) : base(connection, "DBPrestaConnectData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Clients
        {
            get
            {
                if ((_Clients == null))
                {
                    _Clients = base.CreateObjectSet<Client>("Clients");
                }
                return _Clients;
            }
        }
        private ObjectSet<Client> _Clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Intervention> Interventions
        {
            get
            {
                if ((_Interventions == null))
                {
                    _Interventions = base.CreateObjectSet<Intervention>("Interventions");
                }
                return _Interventions;
            }
        }
        private ObjectSet<Intervention> _Interventions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Localisation> Localisations
        {
            get
            {
                if ((_Localisations == null))
                {
                    _Localisations = base.CreateObjectSet<Localisation>("Localisations");
                }
                return _Localisations;
            }
        }
        private ObjectSet<Localisation> _Localisations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prestataire> Prestataires
        {
            get
            {
                if ((_Prestataires == null))
                {
                    _Prestataires = base.CreateObjectSet<Prestataire>("Prestataires");
                }
                return _Prestataires;
            }
        }
        private ObjectSet<Prestataire> _Prestataires;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Zone> Zones
        {
            get
            {
                if ((_Zones == null))
                {
                    _Zones = base.CreateObjectSet<Zone>("Zones");
                }
                return _Zones;
            }
        }
        private ObjectSet<Zone> _Zones;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClients(Client client)
        {
            base.AddObject("Clients", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Interventions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInterventions(Intervention intervention)
        {
            base.AddObject("Interventions", intervention);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Localisations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocalisations(Localisation localisation)
        {
            base.AddObject("Localisations", localisation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Prestataires EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrestataires(Prestataire prestataire)
        {
            base.AddObject("Prestataires", prestataire);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Zones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZones(Zone zone)
        {
            base.AddObject("Zones", zone);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        /// <param name="localisation">Initial value of the Localisation property.</param>
        /// <param name="zone">Initial value of the Zone property.</param>
        public static Client CreateClient(global::System.Int32 id, global::System.String nom, global::System.Int32 localisation, global::System.Int32 zone)
        {
            Client client = new Client();
            client.Id = id;
            client.Nom = nom;
            client.Localisation = localisation;
            client.Zone = zone;
            return client;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = value;
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Localisation
        {
            get
            {
                return _Localisation;
            }
            set
            {
                OnLocalisationChanging(value);
                ReportPropertyChanging("Localisation");
                _Localisation = value;
                ReportPropertyChanged("Localisation");
                OnLocalisationChanged();
            }
        }
        private global::System.Int32 _Localisation;
        partial void OnLocalisationChanging(global::System.Int32 value);
        partial void OnLocalisationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Zone
        {
            get
            {
                return _Zone;
            }
            set
            {
                OnZoneChanging(value);
                ReportPropertyChanging("Zone");
                _Zone = value;
                ReportPropertyChanged("Zone");
                OnZoneChanged();
            }
        }
        private global::System.Int32 _Zone;
        partial void OnZoneChanging(global::System.Int32 value);
        partial void OnZoneChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Client_ToLocalisation", "Localisation")]
        public Localisation Localisation1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Client_ToLocalisation", "Localisation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Client_ToLocalisation", "Localisation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Localisation> Localisation1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Client_ToLocalisation", "Localisation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Localisation>("LightSwitchApplication.FK_Client_ToLocalisation", "Localisation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Client_ToZone", "Zone")]
        public Zone Zone1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zone>("LightSwitchApplication.FK_Client_ToZone", "Zone").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zone>("LightSwitchApplication.FK_Client_ToZone", "Zone").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Zone> Zone1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Zone>("LightSwitchApplication.FK_Client_ToZone", "Zone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Zone>("LightSwitchApplication.FK_Client_ToZone", "Zone", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Intervention_ToClient", "Intervention")]
        public EntityCollection<Intervention> Interventions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Intervention>("LightSwitchApplication.FK_Intervention_ToClient", "Intervention");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Intervention>("LightSwitchApplication.FK_Intervention_ToClient", "Intervention", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Intervention")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Intervention : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Intervention object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateDebut">Initial value of the DateDebut property.</param>
        /// <param name="poste">Initial value of the Poste property.</param>
        /// <param name="client">Initial value of the Client property.</param>
        /// <param name="prestataire">Initial value of the Prestataire property.</param>
        public static Intervention CreateIntervention(global::System.Int32 id, global::System.DateTime dateDebut, global::System.String poste, global::System.Int32 client, global::System.Int32 prestataire)
        {
            Intervention intervention = new Intervention();
            intervention.Id = id;
            intervention.DateDebut = dateDebut;
            intervention.Poste = poste;
            intervention.Client = client;
            intervention.Prestataire = prestataire;
            return intervention;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateDebut
        {
            get
            {
                return _DateDebut;
            }
            set
            {
                OnDateDebutChanging(value);
                ReportPropertyChanging("DateDebut");
                _DateDebut = value;
                ReportPropertyChanged("DateDebut");
                OnDateDebutChanged();
            }
        }
        private global::System.DateTime _DateDebut;
        partial void OnDateDebutChanging(global::System.DateTime value);
        partial void OnDateDebutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateFin
        {
            get
            {
                return _DateFin;
            }
            set
            {
                OnDateFinChanging(value);
                ReportPropertyChanging("DateFin");
                _DateFin = value;
                ReportPropertyChanged("DateFin");
                OnDateFinChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateFin;
        partial void OnDateFinChanging(Nullable<global::System.DateTime> value);
        partial void OnDateFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Poste
        {
            get
            {
                return _Poste;
            }
            set
            {
                OnPosteChanging(value);
                ReportPropertyChanging("Poste");
                _Poste = value;
                ReportPropertyChanged("Poste");
                OnPosteChanged();
            }
        }
        private global::System.String _Poste;
        partial void OnPosteChanging(global::System.String value);
        partial void OnPosteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Client
        {
            get
            {
                return _Client;
            }
            set
            {
                OnClientChanging(value);
                ReportPropertyChanging("Client");
                _Client = value;
                ReportPropertyChanged("Client");
                OnClientChanged();
            }
        }
        private global::System.Int32 _Client;
        partial void OnClientChanging(global::System.Int32 value);
        partial void OnClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Prestataire
        {
            get
            {
                return _Prestataire;
            }
            set
            {
                OnPrestataireChanging(value);
                ReportPropertyChanging("Prestataire");
                _Prestataire = value;
                ReportPropertyChanged("Prestataire");
                OnPrestataireChanged();
            }
        }
        private global::System.Int32 _Prestataire;
        partial void OnPrestataireChanging(global::System.Int32 value);
        partial void OnPrestataireChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Intervention_ToClient", "Client")]
        public Client Client1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("LightSwitchApplication.FK_Intervention_ToClient", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("LightSwitchApplication.FK_Intervention_ToClient", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> Client1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("LightSwitchApplication.FK_Intervention_ToClient", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("LightSwitchApplication.FK_Intervention_ToClient", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Intervention_ToPrestataire", "Prestataire")]
        public Prestataire Prestataire1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prestataire>("LightSwitchApplication.FK_Intervention_ToPrestataire", "Prestataire").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prestataire>("LightSwitchApplication.FK_Intervention_ToPrestataire", "Prestataire").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Prestataire> Prestataire1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prestataire>("LightSwitchApplication.FK_Intervention_ToPrestataire", "Prestataire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Prestataire>("LightSwitchApplication.FK_Intervention_ToPrestataire", "Prestataire", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Localisation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Localisation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Localisation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        public static Localisation CreateLocalisation(global::System.Int32 id, global::System.String latitude, global::System.String longitude)
        {
            Localisation localisation = new Localisation();
            localisation.Id = id;
            localisation.Latitude = latitude;
            localisation.Longitude = longitude;
            return localisation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = value;
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.String _Latitude;
        partial void OnLatitudeChanging(global::System.String value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = value;
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.String _Longitude;
        partial void OnLongitudeChanging(global::System.String value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdresseComplete
        {
            get
            {
                return _AdresseComplete;
            }
            set
            {
                OnAdresseCompleteChanging(value);
                ReportPropertyChanging("AdresseComplete");
                _AdresseComplete = value;
                ReportPropertyChanged("AdresseComplete");
                OnAdresseCompleteChanged();
            }
        }
        private global::System.String _AdresseComplete;
        partial void OnAdresseCompleteChanging(global::System.String value);
        partial void OnAdresseCompleteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Client_ToLocalisation", "Client")]
        public EntityCollection<Client> Clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Client>("LightSwitchApplication.FK_Client_ToLocalisation", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Client>("LightSwitchApplication.FK_Client_ToLocalisation", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Prestataire_ToLocalisation", "Prestataire")]
        public EntityCollection<Prestataire> Prestataires
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Prestataire>("LightSwitchApplication.FK_Prestataire_ToLocalisation", "Prestataire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Prestataire>("LightSwitchApplication.FK_Prestataire_ToLocalisation", "Prestataire", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Zone_ToLocalisationNO", "Zone")]
        public EntityCollection<Zone> Zones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Zone>("LightSwitchApplication.FK_Zone_ToLocalisationNO", "Zone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Zone>("LightSwitchApplication.FK_Zone_ToLocalisationNO", "Zone", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Zone_ToLocalisationSE", "Zone")]
        public EntityCollection<Zone> Zones1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Zone>("LightSwitchApplication.FK_Zone_ToLocalisationSE", "Zone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Zone>("LightSwitchApplication.FK_Zone_ToLocalisationSE", "Zone", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Prestataire")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prestataire : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Prestataire object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        /// <param name="prenom">Initial value of the Prenom property.</param>
        /// <param name="localisation">Initial value of the Localisation property.</param>
        public static Prestataire CreatePrestataire(global::System.Int32 id, global::System.String nom, global::System.String prenom, global::System.Int32 localisation)
        {
            Prestataire prestataire = new Prestataire();
            prestataire.Id = id;
            prestataire.Nom = nom;
            prestataire.Prenom = prenom;
            prestataire.Localisation = localisation;
            return prestataire;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = value;
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = value;
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailPro
        {
            get
            {
                return _EmailPro;
            }
            set
            {
                OnEmailProChanging(value);
                ReportPropertyChanging("EmailPro");
                _EmailPro = value;
                ReportPropertyChanged("EmailPro");
                OnEmailProChanged();
            }
        }
        private global::System.String _EmailPro;
        partial void OnEmailProChanging(global::System.String value);
        partial void OnEmailProChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailPerso
        {
            get
            {
                return _EmailPerso;
            }
            set
            {
                OnEmailPersoChanging(value);
                ReportPropertyChanging("EmailPerso");
                _EmailPerso = value;
                ReportPropertyChanged("EmailPerso");
                OnEmailPersoChanged();
            }
        }
        private global::System.String _EmailPerso;
        partial void OnEmailPersoChanging(global::System.String value);
        partial void OnEmailPersoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = value;
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompteSkype
        {
            get
            {
                return _CompteSkype;
            }
            set
            {
                OnCompteSkypeChanging(value);
                ReportPropertyChanging("CompteSkype");
                _CompteSkype = value;
                ReportPropertyChanged("CompteSkype");
                OnCompteSkypeChanged();
            }
        }
        private global::System.String _CompteSkype;
        partial void OnCompteSkypeChanging(global::System.String value);
        partial void OnCompteSkypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Localisation
        {
            get
            {
                return _Localisation;
            }
            set
            {
                OnLocalisationChanging(value);
                ReportPropertyChanging("Localisation");
                _Localisation = value;
                ReportPropertyChanged("Localisation");
                OnLocalisationChanged();
            }
        }
        private global::System.Int32 _Localisation;
        partial void OnLocalisationChanging(global::System.Int32 value);
        partial void OnLocalisationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Intervention_ToPrestataire", "Intervention")]
        public EntityCollection<Intervention> Interventions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Intervention>("LightSwitchApplication.FK_Intervention_ToPrestataire", "Intervention");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Intervention>("LightSwitchApplication.FK_Intervention_ToPrestataire", "Intervention", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Prestataire_ToLocalisation", "Localisation")]
        public Localisation Localisation1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Prestataire_ToLocalisation", "Localisation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Prestataire_ToLocalisation", "Localisation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Localisation> Localisation1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Prestataire_ToLocalisation", "Localisation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Localisation>("LightSwitchApplication.FK_Prestataire_ToLocalisation", "Localisation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Zone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Zone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Zone object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        /// <param name="localisationNO">Initial value of the LocalisationNO property.</param>
        /// <param name="localisationSE">Initial value of the LocalisationSE property.</param>
        public static Zone CreateZone(global::System.Int32 id, global::System.String nom, global::System.Int32 localisationNO, global::System.Int32 localisationSE)
        {
            Zone zone = new Zone();
            zone.Id = id;
            zone.Nom = nom;
            zone.LocalisationNO = localisationNO;
            zone.LocalisationSE = localisationSE;
            return zone;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = value;
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocalisationNO
        {
            get
            {
                return _LocalisationNO;
            }
            set
            {
                OnLocalisationNOChanging(value);
                ReportPropertyChanging("LocalisationNO");
                _LocalisationNO = value;
                ReportPropertyChanged("LocalisationNO");
                OnLocalisationNOChanged();
            }
        }
        private global::System.Int32 _LocalisationNO;
        partial void OnLocalisationNOChanging(global::System.Int32 value);
        partial void OnLocalisationNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocalisationSE
        {
            get
            {
                return _LocalisationSE;
            }
            set
            {
                OnLocalisationSEChanging(value);
                ReportPropertyChanging("LocalisationSE");
                _LocalisationSE = value;
                ReportPropertyChanged("LocalisationSE");
                OnLocalisationSEChanged();
            }
        }
        private global::System.Int32 _LocalisationSE;
        partial void OnLocalisationSEChanging(global::System.Int32 value);
        partial void OnLocalisationSEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Client_ToZone", "Client")]
        public EntityCollection<Client> Clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Client>("LightSwitchApplication.FK_Client_ToZone", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Client>("LightSwitchApplication.FK_Client_ToZone", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Zone_ToLocalisationNO", "Localisation")]
        public Localisation Localisation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Zone_ToLocalisationNO", "Localisation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Zone_ToLocalisationNO", "Localisation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Localisation> LocalisationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Zone_ToLocalisationNO", "Localisation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Localisation>("LightSwitchApplication.FK_Zone_ToLocalisationNO", "Localisation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FK_Zone_ToLocalisationSE", "Localisation")]
        public Localisation Localisation1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Zone_ToLocalisationSE", "Localisation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Zone_ToLocalisationSE", "Localisation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Localisation> Localisation1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Localisation>("LightSwitchApplication.FK_Zone_ToLocalisationSE", "Localisation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Localisation>("LightSwitchApplication.FK_Zone_ToLocalisationSE", "Localisation", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
