

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Prestataire : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Prestataire entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Prestataire()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Prestataire(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Prestataire> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Prestataire.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataire_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prestataire_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string NomPrenom
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.NomPrenom);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NomPrenom_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NomPrenom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Nom
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Nom);
            }
            set
            {
                global::LightSwitchApplication.Prestataire.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Nom, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nom_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nom_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Prenom
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Prenom);
            }
            set
            {
                global::LightSwitchApplication.Prestataire.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Prenom, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prenom_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prenom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prenom_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EmailPro
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.EmailPro);
            }
            set
            {
                global::LightSwitchApplication.Prestataire.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.EmailPro, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailPro_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailPro_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailPro_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EmailPerso
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.EmailPerso);
            }
            set
            {
                global::LightSwitchApplication.Prestataire.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.EmailPerso, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailPerso_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailPerso_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailPerso_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Mobile
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Mobile);
            }
            set
            {
                global::LightSwitchApplication.Prestataire.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Mobile, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mobile_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mobile_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mobile_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CompteSkype
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.CompteSkype);
            }
            set
            {
                global::LightSwitchApplication.Prestataire.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.CompteSkype, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompteSkype_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompteSkype_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompteSkype_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Intervention> Interventions
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Interventions);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Intervention> InterventionsQuery
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetQuery(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Interventions);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Localisation Localisation1
        {
            get
            {
                return global::LightSwitchApplication.Prestataire.DetailsClass.GetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Localisation1);
            }
            set
            {
                global::LightSwitchApplication.Prestataire.DetailsClass.SetValue(this, global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Localisation1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisation1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisation1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Localisation1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Prestataire,
                global::LightSwitchApplication.Prestataire.DetailsClass,
                global::LightSwitchApplication.Prestataire.DetailsClass.IImplementation,
                global::LightSwitchApplication.Prestataire.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass>.Entry
                __PrestataireEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass>.Entry(
                    global::LightSwitchApplication.Prestataire.DetailsClass.__Prestataire_CreateNew,
                    global::LightSwitchApplication.Prestataire.DetailsClass.__Prestataire_Created,
                    global::LightSwitchApplication.Prestataire.DetailsClass.__Prestataire_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Prestataire __Prestataire_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Prestataire> es)
            {
                return new global::LightSwitchApplication.Prestataire(es);
            }
            private static void __Prestataire_Created(global::LightSwitchApplication.Prestataire e)
            {
                e.Prestataire_Created();
            }
            private static bool __Prestataire_AllowSaveWithErrors(global::LightSwitchApplication.Prestataire e)
            {
                bool result = false;
                e.Prestataire_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Prestataire.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string> NomPrenom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.NomPrenom) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string> Nom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Nom) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string> Prenom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Prenom) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string> EmailPro
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.EmailPro) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string> EmailPerso
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.EmailPerso) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string> Mobile
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Mobile) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string> CompteSkype
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.CompteSkype) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Intervention> Interventions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Interventions) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Intervention>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Localisation> Localisation1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Localisation1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Localisation>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Nom { get; set; }
                new string Prenom { get; set; }
                new string EmailPro { get; set; }
                new string EmailPerso { get; set; }
                new string Mobile { get; set; }
                new string CompteSkype { get; set; }
                new global::System.Collections.IEnumerable Interventions { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Localisation1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, int>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Prestataire e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Prestataire e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry
                    NomPrenom = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry(
                        "NomPrenom",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._NomPrenom_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._NomPrenom_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._NomPrenom_ComputeValue);
                private static void _NomPrenom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._NomPrenom, sf);
                }
                private static void _NomPrenom_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NomPrenom_Validate(r);
                }
                private static string _NomPrenom_ComputeValue(global::LightSwitchApplication.Prestataire e)
                {
                    string value = default(string);
                    e.NomPrenom_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry
                    Nom = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry(
                        "Nom",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Nom_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Nom_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Nom_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Nom_GetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Nom_SetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Nom_OnValueChanged);
                private static void _Nom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._Nom, sf);
                }
                private static bool _Nom_ComputeIsReadOnly(global::LightSwitchApplication.Prestataire e)
                {
                    bool result = false;
                    e.Nom_IsReadOnly(ref result);
                    return result;
                }
                private static void _Nom_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Nom_Validate(r);
                }
                private static string _Nom_GetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.Nom;
                }
                private static void _Nom_SetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Nom = v;
                }
                private static void _Nom_OnValueChanged(global::LightSwitchApplication.Prestataire e)
                {
                    e.Nom_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry
                    Prenom = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry(
                        "Prenom",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Prenom_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Prenom_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Prenom_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Prenom_GetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Prenom_SetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Prenom_OnValueChanged);
                private static void _Prenom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._Prenom, sf);
                }
                private static bool _Prenom_ComputeIsReadOnly(global::LightSwitchApplication.Prestataire e)
                {
                    bool result = false;
                    e.Prenom_IsReadOnly(ref result);
                    return result;
                }
                private static void _Prenom_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Prenom_Validate(r);
                }
                private static string _Prenom_GetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.Prenom;
                }
                private static void _Prenom_SetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Prenom = v;
                }
                private static void _Prenom_OnValueChanged(global::LightSwitchApplication.Prestataire e)
                {
                    e.Prenom_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry
                    EmailPro = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry(
                        "EmailPro",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPro_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPro_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPro_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPro_GetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPro_SetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPro_OnValueChanged);
                private static void _EmailPro_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._EmailPro, sf);
                }
                private static bool _EmailPro_ComputeIsReadOnly(global::LightSwitchApplication.Prestataire e)
                {
                    bool result = false;
                    e.EmailPro_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmailPro_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmailPro_Validate(r);
                }
                private static string _EmailPro_GetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.EmailPro;
                }
                private static void _EmailPro_SetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EmailPro = v;
                }
                private static void _EmailPro_OnValueChanged(global::LightSwitchApplication.Prestataire e)
                {
                    e.EmailPro_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry
                    EmailPerso = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry(
                        "EmailPerso",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPerso_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPerso_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPerso_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPerso_GetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPerso_SetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._EmailPerso_OnValueChanged);
                private static void _EmailPerso_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._EmailPerso, sf);
                }
                private static bool _EmailPerso_ComputeIsReadOnly(global::LightSwitchApplication.Prestataire e)
                {
                    bool result = false;
                    e.EmailPerso_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmailPerso_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmailPerso_Validate(r);
                }
                private static string _EmailPerso_GetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.EmailPerso;
                }
                private static void _EmailPerso_SetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EmailPerso = v;
                }
                private static void _EmailPerso_OnValueChanged(global::LightSwitchApplication.Prestataire e)
                {
                    e.EmailPerso_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry
                    Mobile = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry(
                        "Mobile",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Mobile_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Mobile_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Mobile_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Mobile_GetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Mobile_SetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Mobile_OnValueChanged);
                private static void _Mobile_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._Mobile, sf);
                }
                private static bool _Mobile_ComputeIsReadOnly(global::LightSwitchApplication.Prestataire e)
                {
                    bool result = false;
                    e.Mobile_IsReadOnly(ref result);
                    return result;
                }
                private static void _Mobile_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Mobile_Validate(r);
                }
                private static string _Mobile_GetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.Mobile;
                }
                private static void _Mobile_SetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Mobile = v;
                }
                private static void _Mobile_OnValueChanged(global::LightSwitchApplication.Prestataire e)
                {
                    e.Mobile_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry
                    CompteSkype = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Entry(
                        "CompteSkype",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._CompteSkype_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._CompteSkype_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._CompteSkype_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._CompteSkype_GetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._CompteSkype_SetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._CompteSkype_OnValueChanged);
                private static void _CompteSkype_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._CompteSkype, sf);
                }
                private static bool _CompteSkype_ComputeIsReadOnly(global::LightSwitchApplication.Prestataire e)
                {
                    bool result = false;
                    e.CompteSkype_IsReadOnly(ref result);
                    return result;
                }
                private static void _CompteSkype_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CompteSkype_Validate(r);
                }
                private static string _CompteSkype_GetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.CompteSkype;
                }
                private static void _CompteSkype_SetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CompteSkype = v;
                }
                private static void _CompteSkype_OnValueChanged(global::LightSwitchApplication.Prestataire e)
                {
                    e.CompteSkype_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Intervention>.Entry
                    Interventions = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Intervention>.Entry(
                        "Interventions",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Interventions_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Interventions_GetReferencedEntities,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Interventions_GetEntityCollection);
                private static void _Interventions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Intervention>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._Interventions, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Intervention> _Interventions_GetReferencedEntities(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Intervention, global::LightSwitchApplication.Intervention.DetailsClass>(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Interventions, ref d._Interventions);
                }
                private static global::System.Collections.IEnumerable _Interventions_GetEntityCollection(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.Interventions;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Localisation>.Entry
                    Localisation1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Localisation>.Entry(
                        "Localisation1",
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Localisation1_Stub,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Localisation1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Localisation1_Validate,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Localisation1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Localisation1_GetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Localisation1_SetImplementationValue,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Localisation1_Refresh,
                        global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties._Localisation1_OnValueChanged);
                private static void _Localisation1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Prestataire.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Localisation>.Data> c, global::LightSwitchApplication.Prestataire.DetailsClass d, object sf)
                {
                    c(d, ref d._Localisation1, sf);
                }
                private static bool _Localisation1_ComputeIsReadOnly(global::LightSwitchApplication.Prestataire e)
                {
                    bool result = false;
                    e.Localisation1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Localisation1_Validate(global::LightSwitchApplication.Prestataire e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Localisation1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Localisation1_GetCoreImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.ImplementationEntity.Localisation1;
                }
                private static global::LightSwitchApplication.Localisation _Localisation1_GetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Localisation, global::LightSwitchApplication.Localisation.DetailsClass>(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Localisation1, ref d._Localisation1);
                }
                private static void _Localisation1_SetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass d, global::LightSwitchApplication.Localisation v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Localisation1, ref d._Localisation1, (i, ev) => i.Localisation1 = ev, v);
                }
                private static void _Localisation1_Refresh(global::LightSwitchApplication.Prestataire.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Prestataire.DetailsClass.PropertySetProperties.Localisation1, ref d._Localisation1);
                }
                private static void _Localisation1_OnValueChanged(global::LightSwitchApplication.Prestataire e)
                {
                    e.Localisation1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data _NomPrenom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data _Nom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data _Prenom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data _EmailPro;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data _EmailPerso;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data _Mobile;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, string>.Data _CompteSkype;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Intervention>.Data _Interventions;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Prestataire, global::LightSwitchApplication.Prestataire.DetailsClass, global::LightSwitchApplication.Localisation>.Data _Localisation1;
            
        }
    
        #endregion
    }
    
    #endregion
}
